#!/usr/bin/env bash

# check for pip.
if ! [ -x "$(command -v pip)" ]; then
  echo 'Error: pip is not available.' >&2
  exit 1
fi

# install pip-able requirements.
pip install -r config/requirements.txt

# install degnorm.
python setup.py install