site_name: DegNorm
nav:
- Home: 'index.md'
- How-Tos:
    - 'Installation': 'howtos/installation.md'
    - 'Running DegNorm': 'howtos/run_the_pipeline.md'
    - 'Speed enhancements': 'howtos/speedups.md'
    - 'Posthoc analysis': 'howtos/posthoc_analysis.md'
- About:
    - 'License': 'about/license.md'
    - 'Contact': 'about/contact.md'
    - 'Release notes': 'about/release.md'
theme:
  name: null
  custom_dir: 'cinder/'
