site_name: DegNorm
nav:
- Home: 'index.md'
- How-Tos:
    - 'Installation': 'howtos/installation.md'
    - 'Running DegNorm': 'howtos/run_the_pipeline.md'
    - 'Speed Enhancements': 'howtos/speedups.md'
    - 'Posthoc Analysis': 'howtos/posthoc_analysis.md'
- About:
    - 'License': 'about/license.md'
    - 'Release Notes': 'about/release.md'
theme:
  name: null
  custom_dir: 'cinder/'
